/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as HimusadminIndexRouteImport } from './routes/himusadmin.index'
import { Route as HimusadminIdRouteImport } from './routes/himusadmin.$id'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as HimusadminBlogIndexRouteImport } from './routes/himusadmin.blog.index'
import { Route as HimusadminBlogIdRouteImport } from './routes/himusadmin.blog.$id'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HimusadminIndexRoute = HimusadminIndexRouteImport.update({
  id: '/himusadmin/',
  path: '/himusadmin/',
  getParentRoute: () => rootRouteImport,
} as any)
const HimusadminIdRoute = HimusadminIdRouteImport.update({
  id: '/himusadmin/$id',
  path: '/himusadmin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HimusadminBlogIndexRoute = HimusadminBlogIndexRouteImport.update({
  id: '/himusadmin/blog/',
  path: '/himusadmin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const HimusadminBlogIdRoute = HimusadminBlogIdRouteImport.update({
  id: '/himusadmin/blog/$id',
  path: '/himusadmin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/himusadmin/$id': typeof HimusadminIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/himusadmin/': typeof HimusadminIndexRoute
  '/himusadmin/blog/$id': typeof HimusadminBlogIdRoute
  '/himusadmin/blog/': typeof HimusadminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/himusadmin/$id': typeof HimusadminIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog': typeof BlogIndexRoute
  '/himusadmin': typeof HimusadminIndexRoute
  '/himusadmin/blog/$id': typeof HimusadminBlogIdRoute
  '/himusadmin/blog': typeof HimusadminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/himusadmin/$id': typeof HimusadminIdRoute
  '/p/$slug': typeof PSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/himusadmin/': typeof HimusadminIndexRoute
  '/himusadmin/blog/$id': typeof HimusadminBlogIdRoute
  '/himusadmin/blog/': typeof HimusadminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/blog/$slug'
    | '/himusadmin/$id'
    | '/p/$slug'
    | '/blog/'
    | '/himusadmin/'
    | '/himusadmin/blog/$id'
    | '/himusadmin/blog/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog/$slug'
    | '/himusadmin/$id'
    | '/p/$slug'
    | '/blog'
    | '/himusadmin'
    | '/himusadmin/blog/$id'
    | '/himusadmin/blog'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/blog/$slug'
    | '/himusadmin/$id'
    | '/p/$slug'
    | '/blog/'
    | '/himusadmin/'
    | '/himusadmin/blog/$id'
    | '/himusadmin/blog/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  HimusadminIdRoute: typeof HimusadminIdRoute
  PSlugRoute: typeof PSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  HimusadminIndexRoute: typeof HimusadminIndexRoute
  HimusadminBlogIdRoute: typeof HimusadminBlogIdRoute
  HimusadminBlogIndexRoute: typeof HimusadminBlogIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himusadmin/': {
      id: '/himusadmin/'
      path: '/himusadmin'
      fullPath: '/himusadmin/'
      preLoaderRoute: typeof HimusadminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himusadmin/$id': {
      id: '/himusadmin/$id'
      path: '/himusadmin/$id'
      fullPath: '/himusadmin/$id'
      preLoaderRoute: typeof HimusadminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himusadmin/blog/': {
      id: '/himusadmin/blog/'
      path: '/himusadmin/blog'
      fullPath: '/himusadmin/blog/'
      preLoaderRoute: typeof HimusadminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/himusadmin/blog/$id': {
      id: '/himusadmin/blog/$id'
      path: '/himusadmin/blog/$id'
      fullPath: '/himusadmin/blog/$id'
      preLoaderRoute: typeof HimusadminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BlogSlugRoute: BlogSlugRoute,
  HimusadminIdRoute: HimusadminIdRoute,
  PSlugRoute: PSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  HimusadminIndexRoute: HimusadminIndexRoute,
  HimusadminBlogIdRoute: HimusadminBlogIdRoute,
  HimusadminBlogIndexRoute: HimusadminBlogIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
