/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminBlogIndexRouteImport } from './routes/admin.blog.index'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/admin/$id',
  path: '/admin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/admin/blog/',
  path: '/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$id': typeof AdminIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$id': typeof AdminIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/$id': typeof AdminIdRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/$id'
    | '/blog/$slug'
    | '/p/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/$id'
    | '/blog/$slug'
    | '/p/$slug'
    | '/admin'
    | '/blog'
    | '/admin/blog'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/$id'
    | '/blog/$slug'
    | '/p/$slug'
    | '/admin/'
    | '/blog/'
    | '/admin/blog/'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminIdRoute: typeof AdminIdRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PSlugRoute: typeof PSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/admin/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/admin/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminIdRoute: AdminIdRoute,
  BlogSlugRoute: BlogSlugRoute,
  PSlugRoute: PSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
